package se.curtrune.lucy.services

object ServiceConstants {
    val ACTION_START_STOPWATCH = "ACTION_START_STOPWATCH"
    val ACTION_RESUME_STOPWATCH = "ACTION_RESUME_STOPWATCH"
    val ACTION_PAUSE_STOPWATCH = "ACTION_PAUSE_STOPWATCH"
    val ACTION_CANCEL_STOPWATCH = "ACTION_CANCEL_STOPWATCH"
}