package se.curtrune.lucy.services

object TimeServiceConstants {
    const val ACTION_START_OR_RESUME_STOPWATCH = "ACTION_START_OR_RESUME_STOPWATCH"
    const val ACTION_PAUSE_STOPWATCH = "ACTION_PAUSE_STOPWATCH"
    const val ACTION_STOP_STOPWATCH = "ACTION_STOP_STOPWATCH"
    const val ACTION_CANCEL_STOPWATCH = "ACTION_CANCEL_STOPWATCH"

    const val ACTION_START_COUNTDOWN_TIMER = "ACTION_START_COUNTDOWN_TIMER"
    const val ACTION_PAUSE_COUNTDOWN_TIMER = "ACTION_PAUSE_COUNTDOWN_TIMER"
    const val ACTION_RESUME_COUNTDOWN_TIMER = "ACTION_RESUME_COUNTDOWN_TIMER"
    const val ACTION_CANCEL_COUNTDOWN_TIMER = "ACTION_CANCEL_COUNTDOWN_TIMER"

    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
    const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
    const val NOTIFICATION_ID = 1

    const val ACTION_STOPWATCH_ACTIVITY = "ACTION_STOPWATCH_ACTIVITY"
}