package se.curtrune.lucy.classes;

import java.io.Serializable;

public enum CallingActivity implements Serializable {
    ITEMS_ACTIVITY, TODAY_ACTIVITY, STATISTICS_ACTIVITY, CALENDER_FRAGMENT, ENCHILADA_FRAGMENT, APPOINTMENT_FRAGMENT, SEQUENCE_ACTIVITY, APPOINTMENTS_FRAGMENT, TODO_FRAGMENT
}
